#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.extract_prze_NC_009153_3.out
#PBS -e $PBS_JOBID.extract_prze_NC_009153_3.err
#PBS -N extract_prze_NC_009153_3.pbs
#PBS -q batch

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_gatk/without_Prze

module load bcftools
bcftools view -S ../../horse_genomes_IDs.txt --min-ac 1 ../NC_009153_3.genotyped.vcf.gz > NC_009153_3.genotyped.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip NC_009153_3.genotyped.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix NC_009153_3.genotyped.vcf.gz
