#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=06:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_Arabian.out
#PBS -e $PBS_JOBID.bcftools_view_Arabian.err
#PBS -N bcftools_view_Arabian.pbs
#PBS -q small
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools view -S horse_ids_all.txt --min-ac 1 thesis_intersect.vcf.gz > thesis_intersect_without_Prze.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_without_Prze.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_without_Prze.vcf.gz
