#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.SnpSift_filter_NC_001640_1.out
#PBS -e $PBS_JOBID.SnpSift_filter_NC_001640_1.err
#PBS -N SnpSift_filter_NC_001640_1.pbs
#PBS -q lab

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs/breed_rare_common_snpeff/

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx4g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "(ANN[0].IMPACT has 'HIGH')" rare_common_breed_snpeff.vcf.gz > rare_common_breed_high.vcf
java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx4g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "(ANN[*].IMPACT = 'MODERATE')" rare_common_breed_snpeff.vcf.gz > rare_common_breed_moderate.vcf
java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx4g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "(ANN[*].IMPACT = 'LOW')" rare_common_breed_snpeff.vcf.gz > rare_common_breed_low.vcf

/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip rare_common_breed_high.vcf
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix rare_common_breed_high.vcf.gz
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip rare_common_breed_moderate.vcf
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix rare_common_breed_moderate.vcf.gz
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip rare_common_breed_low.vcf
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix rare_common_breed_low.vcf.gz

module load bcftools
bcftools stats rare_common_breed_high.vcf.gz > rare_common_breed_high.vcf.gz.stats
bcftools stats rare_common_breed_moderate.vcf.gz > rare_common_breed_moderate.vcf.gz.stats
bcftools stats rare_common_breed_low.vcf.gz > rare_common_breed_low.vcf.gz.stats
