#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.intersect_joint_NC_009152_3.out
#PBS -e $PBS_JOBID.intersect_joint_NC_009152_3.err
#PBS -N intersect_joint_NC_009152_3.pbs
#PBS -q lab
source /home/mccuem/shared/.local/conda/bin/activate gatk4_4.1.0

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/

gatk --java-options "-Xmx4g" SelectVariants -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/GCF_002863925.1_EquCab3.0_genomic/GCF_002863925.1_EquCab3.0_genomic.fna -V joint_union/NC_009152_3_union_joint.vcf.gz -O joint_intersect_without_Prze/NC_009152_3_intersect_joint.vcf.gz --select 'set == "Intersection";'
