#!/bin/bash -l
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_stats.genotyped.vcf.gz.out
#PBS -e $PBS_JOBID.bcftools_stats.genotyped.vcf.gz.err
#PBS -N bcftools_stats.genotyped.vcf.gz.pbs
#PBS -q lab
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_gatk_without_Prze/chrom_x

for i in  NC_009175_3 ; do bcftools stats -s HF13B ${i}.genotyped.vcf.gz > ind_bcftools_stats_files/HF13B_Other_${i}.stats;done
