#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isex_TB.out
#PBS -e $PBS_JOBID.bcftools_isex_TB.err
#PBS -N bcftools_isec_TB.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs

bcftools isec -p TB_rare_Arabian_common TB_rare.vcf.gz Arabian_common.vcf.gz
bcftools isec -p TB_rare_Belgian_common TB_rare.vcf.gz Belgian_common.vcf.gz
bcftools isec -p TB_rare_Clydesdale_common TB_rare.vcf.gz Clydesdale_common.vcf.gz
bcftools isec -p TB_rare_Icelandic_common TB_rare.vcf.gz Icelandic_common.vcf.gz
bcftools isec -p TB_rare_Morgan_common TB_rare.vcf.gz Morgan_common.vcf.gz
bcftools isec -p TB_rare_QH_common TB_rare.vcf.gz QH_common.vcf.gz
bcftools isec -p TB_rare_STB_common TB_rare.vcf.gz STB_common.vcf.gz
bcftools isec -p TB_rare_WP_common TB_rare.vcf.gz WP_common.vcf.gz
bcftools isec -p TB_rare_Shetland_common TB_rare.vcf.gz Shetland_common.vcf.gz
