#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isex_Belgian.out
#PBS -e $PBS_JOBID.bcftools_isex_Belgian.err
#PBS -N bcftools_isec_Belgian.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs

bcftools isec -p Belgian_rare_Arabian_common Belgian_rare.vcf.gz Arabian_common.vcf.gz
bcftools isec -p Belgian_rare_Clydesdale_common Belgian_rare.vcf.gz Clydesdale_common.vcf.gz
bcftools isec -p Belgian_rare_Icelandic_common Belgian_rare.vcf.gz Icelandic_common.vcf.gz
bcftools isec -p Belgian_rare_Morgan_common Belgian_rare.vcf.gz Morgan_common.vcf.gz
bcftools isec -p Belgian_rare_QH_common Belgian_rare.vcf.gz QH_common.vcf.gz
bcftools isec -p Belgian_rare_STB_common Belgian_rare.vcf.gz STB_common.vcf.gz
bcftools isec -p Belgian_rare_TB_common Belgian_rare.vcf.gz TB_common.vcf.gz
bcftools isec -p Belgian_rare_WP_common Belgian_rare.vcf.gz WP_common.vcf.gz
bcftools isec -p Belgian_rare_Shetland_common Belgian_rare.vcf.gz Shetland_common.vcf.gz
