#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isex_STB.out
#PBS -e $PBS_JOBID.bcftools_isex_STB.err
#PBS -N bcftools_isec_STB.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs

bcftools isec -p STB_rare_Arabian_common STB_rare.vcf.gz Arabian_common.vcf.gz
bcftools isec -p STB_rare_Belgian_common STB_rare.vcf.gz Belgian_common.vcf.gz
bcftools isec -p STB_rare_Clydesdale_common STB_rare.vcf.gz Clydesdale_common.vcf.gz
bcftools isec -p STB_rare_Icelandic_common STB_rare.vcf.gz Icelandic_common.vcf.gz
bcftools isec -p STB_rare_Morgan_common STB_rare.vcf.gz Morgan_common.vcf.gz
bcftools isec -p STB_rare_QH_common STB_rare.vcf.gz QH_common.vcf.gz
bcftools isec -p STB_rare_TB_common STB_rare.vcf.gz TB_common.vcf.gz
bcftools isec -p STB_rare_WP_common STB_rare.vcf.gz WP_common.vcf.gz
bcftools isec -p STB_rare_Shetland_common STB_rare.vcf.gz Shetland_common.vcf.gz
