#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isec_Arabian_pop.out
#PBS -e $PBS_JOBID.bcftools_isec_Arabian_pop.err
#PBS -N bcftools_isec_Arabian_pop.pbs
#PBS -q small
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/rare_common_breed_pop/breed_pop_rare_common_vcfs

bcftools isec -p Arabian_rare_pop_common breed_rare_common_vcfs/Arabian_rare.vcf.gz without_Arabian_common.vcf.gz
