#!/bin/bash -l
#PBS -l nodes=1:ppn=1,walltime=24:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.Extract_variants_NC_001640.1.out
#PBS -e $PBS_JOBID.Extract_variants_NC_001640.1.err
#PBS -N Extract_variants_NC_001640.1.pbs
#PBS -q small
module load bcftools


cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect_without_Prze/split_chromosomes

bcftools view -r NC_001640.1:0-10000 /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect_without_Prze/thesis_intersect.vcf.gz | bcftools stats > NC_001640.1_0_10000.stats
bcftools view -r NC_001640.1:10001-16660 /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect_without_Prze/thesis_intersect.vcf.gz | bcftools stats > NC_001640.1_10001_16660.stats
