#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.union_joint_NC_009153_3.out
#PBS -e $PBS_JOBID.union_joint_NC_009153_3.err
#PBS -N union_joint_NC_009153_3.pbs
#PBS -q lab

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf

java -Xmx4g -jar /home/mccuem/shared/.local/conda/envs/HorseGenomeProject/bin/GenomeAnalysisTK.jar -T CombineVariants -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/GCF_002863925.1_EquCab3.0_genomic/GCF_002863925.1_EquCab3.0_genomic.fna --variant:bcftools joint_bcftools_without_Prze/NC_009153_3.genotyped.vcf.gz --variant:gatk joint_gatk_without_Prze/NC_009153_3.genotyped.vcf.gz -o joint_union/NC_009153_3_union_joint.vcf.gz -nt 4 -genotypeMergeOptions UNSORTED
