#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isex_Arabian.out
#PBS -e $PBS_JOBID.bcftools_isex_Arabian.err
#PBS -N bcftools_isec_Arabian.pbs
#PBS -qlab 
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect/dbsnp

bcftools isec -p dbsnp_intersect /home/mccuem/shared/Projects/HorseGenomeProject/Data/gold_standard/equus_caballus.vcf.gz ../thesis_intersect.vcf.gz
bcftools isec -p dbsnp_intersect /home/mccuem/shared/Projects/HorseGenomeProject/Data/gold_standard/equus_caballus_structural_variations.vcf.gz ../thesis_intersect.vcf.gz
